version: '3.7'

services:
  api:
    image: home-dashboard:latest
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    environment:
      - DOMAIN=${DOMAIN:-localhost}
      - PORT=${PORT:-8080}
      - KEY_DIRECTORY=${KEY_DIRECTORY:-/keys}
      - DB_HOST=${DB_HOST:-db}
      - DB_USER=${DB_USER?Missing DB_USER}
      - DB_PASSWORD=${DB_PASSWORD?Missing DB_PASSWORD}
      - DB_COLLECTION=${DB_COLLECTION:-dashboard}
    volumes:
      - ${DOCKERDIR?Missing DOCKERDIR}/dashboard/keys:${KEY_DIRECTORY:-/keys}

  db:
    image: mongo
    # Uncomment for enabling outside access to container
    # ports:
      # - "27017:27017"
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=phil
      - MONGO_INITDB_ROOT_PASSWORD=phil
      - MONGO_INITDB_DATABASE=dashboard
    volumes:
      - ${DOCKERDIR}/dashboard/mongo:/data/db
      - ${DOCKERDIR}/dashboard/db/:/docker-entrypoint-initdb.d/
